name: vanilla
description: Vanilla mobile app
version: 1.0.0

dependencies:
  intl: ^0.16.0
  http: ^0.12.1
  fluttertoast: ^4.0.1
  cupertino_icons: ^0.1.3
  random_pk: ^0.0.3
  shimmer: ^1.1.1
  shared_preferences: ^0.5.7+2
  transparent_image: ^1.0.0
  flutter_slidable: ^0.5.4
  flutter_rating: ^0.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter
  redux: ^4.0.0
  flutter_redux: ^0.6.0
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo.png"
flutter:
  uses-material-design: true

  fonts:
    - family: Sans
      fonts:
        - asset: assets/font/OpenSans-Bold.ttf
          weight: 800
        - asset: assets/font/OpenSans-Semibold.ttf
          weight: 600
        - asset: assets/font/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/font/OpenSans-Light.ttf
          weight: 200
    - family: Popins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
    - family: Berlin
      fonts:
        - asset: assets/font/BRLNSDB.TTF
          weight: 700
    - family: Gotik
      fonts:
        - asset: assets/font/GOTHIC.TTF
          weight: 400
        - asset: assets/font/GOTHICB.TTF
          weight: 600

  assets:
    - lang/en.json
    - lang/ar.json
    - assets/img/google.png
    - assets/img/img1.png
    - assets/img/img2.png
    - assets/img/img3.png
    - assets/img/img4.png
    - assets/img/img5.png
    - assets/img/img6.png
    - assets/img/img7.png
    - assets/img/img8.png
    - assets/img/img9.png
    - assets/img/img10.png
    - assets/img/img11.png
    - assets/img/img12.png
    - assets/img/googlewallet.png
    - assets/img/credit.png
    - assets/img/handshake.png
    - assets/img/paypal.png
    - assets/img/icon_facebook.png
    - assets/img/Logo.png
    - assets/img/logowithtext.png
    - assets/img/title_only.png
    - assets/img/Rectangle.png
    - assets/img/girl.png
    - assets/img/loginscreenbackground.png
    - assets/img/backgroundgirl.png
    - assets/img/man.png
    - assets/img/search.png
    - assets/img/search2.png
    - assets/img/chat.png
    - assets/img/notifications-button.png
    - assets/img/banner1.png
    - assets/img/banner2.png
    - assets/img/banner3.png
    - assets/icon/book.png
    - assets/icon/camera.png
    - assets/icon/fashion.png
    - assets/icon/food.png
    - assets/icon/game.png
    - assets/icon/handphone.png
    - assets/icon/health.png
    - assets/icon/mesin.png
    - assets/icon/otomotif.png
    - assets/icon/pc.png
    - assets/icon/sport.png
    - assets/icon/ticket.png
    - assets/imgPromo/Discount1.png
    - assets/imgPromo/Discount2.png
    - assets/imgPromo/Discount3.png
    - assets/imgPromo/Discount4.png
    - assets/imgPromo/Discount5.png
    - assets/imgPromo/Discount6.png
    - assets/img/flashsaleicon.png
    - assets/imgItem/mackbook.jpg
    - assets/imgItem/fashion1.jpg
    - assets/imgItem/flashsale2.jpg
    - assets/imgItem/flashsale3.jpg
    - assets/imgItem/flashsale4.jpg
    - assets/imgItem/flashsale5.jpg
    - assets/imgItem/category1.png
    - assets/imgItem/category2.png
    - assets/imgItem/category3.png
    - assets/imgItem/category4.png
    - assets/imgItem/category5.png
    - assets/imgItem/category6.png
    - assets/imgItem/category7.png
    - assets/imgItem/category8.png
    - assets/imgItem/acesoris1.jpg
    - assets/imgItem/beauty1.jpg
    - assets/imgItem/girl1.jpg
    - assets/imgItem/kids1.jpg
    - assets/imgItem/man1.jpg
    - assets/imgItem/shoes1.jpg
    - assets/imgItem/shoes2.jpg
    - assets/img/notmessage.png
    - assets/img/noNotification.png
    - assets/imgBrand/appleHeader.png
    - assets/imgBrand/fendiHeader.png
    - assets/imgBrand/gucciHeader.png
    - assets/imgBrand/nikeHeader.png
    - assets/imgBrand/samsungHeader.png
    - assets/imgBrand/sonyHeader.png
    - assets/img/womanface.jpg
    - assets/icon/truck.png
    - assets/icon/gender_icon.png
    - assets/icon/chat.png
    - assets/icon/notification.png
    - assets/icon/callcenter.png
    - assets/icon/setting.png
    - assets/icon/aboutapp.png
    - assets/icon/shopping-cart.png
    - assets/icon/message.png
    - assets/img/bannerMan1.png
    - assets/img/bannerMan2.png
    - assets/img/bannerMan3.png
    - assets/img/bannerMan4.png
    - assets/imgCamera/CameraDigital.png
    - assets/imgCamera/CompactCamera.png
    - assets/imgCamera/ActionCamera.png
    - assets/imgCamera/cameraItem1.png
    - assets/imgCamera/cameraItem2.png
    - assets/imgCamera/cameraItem3.png
    - assets/imgCamera/cameraItem4.png
    - assets/imgPromo/imgPromo1.jpg
    - assets/imgPromo/imgPromo2.jpg
    - assets/imgPromo/imgPromo3.jpg
    - assets/imgPromo/imgPromo4.jpg
    - assets/imgPromo/imgPromo5.jpg
    - assets/imgPromo/imgPromo6.jpg
    - assets/imgPromo/imgPromo7.jpg
    - assets/imgPromo/imgPromo8.jpg
    - assets/imgCategoryMan/Man1.jpg
    - assets/imgCategoryMan/Man2.jpg
    - assets/imgCategoryMan/Man3.jpg
    - assets/imgCategoryMan/Man4.jpg
    - assets/imgCategoryMan/Man5.jpg
    - assets/imgCategoryMan/Man6.jpg
    - assets/img/bag.png
    - assets/img/courier.png
    - assets/img/house.png
    - assets/img/order.png
    - assets/img/payment.png
    - assets/icon/girlcallcenter.png
    - assets/img/checklist.png
    - assets/icon/creditAcount.png
    - assets/img/creditCardVisa.png
    - assets/imgBrand/brandNike.jpg
    - assets/imgBrand/brand1.jpg
    - assets/imgBrand/brand2.jpg
    - assets/imgBrand/brand3.jpg
    - assets/imgBrand/brand4.jpg
    - assets/imgBrand/brand5.jpg
    - assets/imgBrand/brand6.jpg
    - assets/imgBrand/brandApple.jpg
    - assets/img/flashsalebanner.png
    - assets/icon/flashSaleIcon.png
    - assets/img/headerProfile.png
    - assets/img/SliderLogin2.png
    - assets/img/SliderLogin3.png
    - assets/img/SliderLogin4.png
    - assets/imgIllustration/IlustrasiMessage.png
    - assets/imgIllustration/IlustrasiOnBoarding1.png
    - assets/imgIllustration/IlustrasiOnBoarding2.png
    - assets/imgIllustration/IlustrasiOnBoarding3.png
    - assets/avatars/avatar-1.jpg
    - assets/avatars/avatar-2.jpg
    - assets/avatars/avatar-3.jpg
    - assets/avatars/avatar-4.jpg
    - assets/avatars/avatar-5.jpg
    - assets/avatars/avatar-6.jpg
    - assets/imgIllustration/IlustrasiCart.png
